language: python

python:
  - '3.11'
  - '3.12'

env:
  - DJANGO_VERSION="Django>=5.2,<6"

install:
  - pip install pyquery
  - pip install -q $DJANGO_VERSION
  - pip install coverage

script: coverage run quicktest.py multi_email_field.tests

after_success:
  - pip install coveralls
  - coveralls
